<a href="https://colab.research.google.com/github/thyungkim/NetDissect-Lite-Reproduce/blob/master/reproduce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import settings
from model_loader import loadmodel
from feature_operation import hook_feature,FeatureOperator
from report import generate_html_summary
from clean import clean
import pandas as pd

In [ ]:
data = pd.read_csv('/content/dataset/broden1_224/index.csv')

In [2]:
!sed -i 's/\r$//' "/content/script/dlbroden.sh"
!sed -i 's/\r$//' "/content/script/dlzoo_example.sh"

In [3]:
!chmod +x "/content/script/dlbroden.sh"
!chmod +x "/content/script/dlzoo_example.sh"

In [4]:
!/content/script/dlbroden.sh
!/content/script/dlzoo_example.sh

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 extracting: broden1_227/images/opensurfaces/113084_color.png  
  inflating: broden1_227/images/opensurfaces/112098.jpg  
 extracting: broden1_227/images/opensurfaces/94348_material.png  
 extracting: broden1_227/images/opensurfaces/85665_color.png  
  inflating: broden1_227/images/opensurfaces/110076_material.png  
  inflating: broden1_227/images/opensurfaces/67048_material.png  
 extracting: broden1_227/images/opensurfaces/105562_color.png  
  inflating: broden1_227/images/opensurfaces/117061.jpg  
  inflating: broden1_227/images/opensurfaces/98135.jpg  
  inflating: broden1_227/images/opensurfaces/66177_material.png  
  inflating: broden1_227/images/opensurfaces/76234.jpg  
 extracting: broden1_227/images/opensurfaces/103337_color.png  
 extracting: broden1_227/images/opensurfaces/111149_material.png  
  inflating: broden1_227/images/opensurfaces/26693.jpg  
  inflating: broden1_227/images/opensurfaces/16372_material.png  
 extracting: broden1_227

In [ ]:
maxfeature

[memmap([[2.18029857, 0.86511129, 1.57594609, ..., 1.80943274, 3.97336674,
          1.70070136],
         [1.15307808, 0.        , 0.65430129, ..., 0.        , 4.19724703,
          0.16749799],
         [4.05456734, 1.79761219, 1.30056465, ..., 0.75141799, 1.4130863 ,
          1.36455476],
         ...,
         [4.21784401, 4.67184448, 0.50736392, ..., 0.78499806, 0.13810338,
          2.43943977],
         [2.84737873, 1.23702133, 0.37516657, ..., 0.        , 0.51356816,
          3.45360398],
         [1.26015556, 0.        , 3.14892054, ..., 1.58890212, 4.41732073,
          0.22479227]])]

In [5]:
fo = FeatureOperator()
model = loadmodel(hook_feature)

############ STEP 1: feature extraction ###############
features, maxfeature = fo.feature_extraction(model=model)



/content/data_loader.py:150: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result[list(np.indices(arr.shape)) + [arr]] = 1


file missing, loading from scratch
self.index right before function return: 1
self.index right before function return: 2
self.index right before function return: 3
self.index right before function return: 4
self.index right before function return: 5
self.index right before function return: 6
self.index right before function return: 7
self.index right before function return: 8
self.index right before function return: 9
self.index right before function return: 10
self.index right before function return: 11
self.index right before function return: 12
self.index right before function return: 13
self.index right before function return: 14
self.index right before function return: 15
self.index right before function return: 16
extracting feature from batch 1 / 15827


/content/feature_operation.py:66: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_var = V(input,volatile=True)


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
extracting feature from batch 14828 / 15827
self.index right before function return: 59325
self.index right before function return: 59326
self.index right before function return: 59327
self.index right before function return: 59328
extracting feature from batch 14829 / 15827
self.index right before function return: 59329
self.index right before function return: 59330
self.index right before function return: 59331
self.index right before function return: 59332
extracting feature from batch 14830 / 15827
self.index right before function return: 59333
self.index right before function return: 59334
self.index right before function return: 59335
self.index right before function return: 59336
extracting feature from batch 14831 / 15827
self.index right before function return: 59337
self.index right before function return: 59338
self.index right before function return: 59339
self.index right before function return: 59340
extracting feature from batch 14832 

In [ ]:
fo.data.size()

63305

In [6]:
for layer_id,layer in enumerate(settings.FEATURE_NAMES):
############ STEP 2: calculating threshold ############
    thresholds = fo.quantile_threshold(features[layer_id],savepath="quantile.npy")

############ STEP 3: calculating IoU scores ###########
    tally_result = fo.tally(features[layer_id],thresholds,savepath="tally.csv")

############ STEP 4: generating results ###############
    generate_html_summary(fo.data, layer,
                          tally_result=tally_result,
                          maxfeature=maxfeature[layer_id],
                          features=features[layer_id],
                          thresholds=thresholds)
    if settings.CLEAN:
        clean()

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 ...
 [-0.62582004 -0.6189388  -0.610343   ... -0.6585075  -0.6685784
  -0.6766404 ]
 [-0.6352634  -0.62835795 -0.61973184 ... -0.66858506 -0.67870915
  -0.6868138 ]
 [-0.6428231  -0.63589823 -0.62724787 ... -0.67665243 -0.6868192
  -0.6949579 ]]
threshold: 4.853631390715011
image: [[[135 131 128]
  [129 126 121]
  [130 125 119]
  ...
  [128 124 141]
  [131 127 144]
  [134 130 147]]

 [[138 134 131]
  [132 129 124]
  [134 129 123]
  ...
  [127 123 140]
  [129 125 142]
  [131 127 144]]

 [[141 138 133]
  [136 133 128]
  [140 136 127]
  ...
  [126 122 139]
  [126 122 139]
  [126 122 139]]

 ...

 [[ 26  23  16]
  [ 43  40  31]
  [ 68  66  54]
  ...
  [112 114 153]
  [112 114 153]
  [113 115 156]]

 [[ 73  69  58]
  [ 88  84  72]
  [109 106  91]
  ...
  [112 114 153]
  [112 114 155]
  [113 115 156]]

 [[113 109  97]
  [118 115 100]
  [124 121 102]
  ...
  [111 113 152]
  [110 112 153]
  [111 113 154]]]
image shape: (224, 224)
feature: [[1.06229652e-02 1

In [7]:
import IPython
IPython.display.HTML(filename='/content/result/pytorch_resnet18_places365_test/html/layer4.html')